name: clicktoeat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  flutter_svg: ^1.0.0
  google_maps_flutter: ^2.1.8
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  flutter_speed_dial: ^6.2.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_driver: ^0.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: FreestyleScript
      fonts:
        - asset: assets/fonts/freestyle_script.ttf
